version: '3.8'

services:
    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        env_file: .env
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        volumes:
            - db:/var/lib/mysql
        container_name: mariadb

    wordpress:
        image: wordpress
        build: ./requirements/wordpress
        env_file: .env
        restart: always
        volumes:
            - web:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        depends_on:
            - mariadb
        container_name: wordpress

    nginx:
        image: nginx
        build: ./requirements/nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - web:/var/www/html
        networks:
            - intra
        depends_on:
            - wordpress
        container_name: nginx

networks:
    intra:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/jun/data/db
    
    web:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/jun/data/web
    